# 模型配置
retrieval:
  # 嵌入模型配置
  embedding_model:
    name: "paraphrase-multilingual-mpnet-base-v2"
    device: "cuda"
    batch_size: 32
    max_length: 512
    normalize_embeddings: true
  
  # 检索配置
  retriever:
    top_k: 20
    similarity_threshold: 0.7
    use_section_filtering: true
    rerank: true
  
  # 重排序配置
  reranker:
    model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
    top_k: 10

# 生成模型配置
generation:
  model:
    name: "microsoft/DialoGPT-medium"
    max_length: 512
    temperature: 0.7
    top_p: 0.9
    do_sample: true
  
  # DRA 动态检索增强配置
  dra:
    enable: true
    max_iterations: 3
    confidence_threshold: 0.8
    adaptive_retrieval: true

# 训练配置
training:
  batch_size: 16
  learning_rate: 2e-5
  num_epochs: 10
  warmup_steps: 500
  save_steps: 1000
  eval_steps: 500